import { useState } from "react";
import { Button } from "@breadcoop/ui";
import { CheckCircle, Plus, Sparkle, Trash, WarningCircle } from "@phosphor-icons/react";
import { generateRegex, type AIExample, type AIProgress } from "../lib/regexAI";

/**
 * AIRegexPanel — plain-English intent → a long RegexLib-subset regex, generated by
 * an LLM running entirely in the browser (Chrome's built-in model when present,
 * otherwise WebLLM on WebGPU — weights stream once and are cached). Every candidate
 * is linted against the onchain subset, compiled, and checked against the example
 * headlines before it is accepted; failures are fed back to the model.
 */
export function AIRegexPanel({
  currentRegex,
  onGenerated,
}: {
  currentRegex: string;
  onGenerated: (regex: string) => void;
}) {
  const [intent, setIntent] = useState("");
  const [examples, setExamples] = useState<AIExample[]>([]);
  const [draft, setDraft] = useState("");
  const [draftShouldMatch, setDraftShouldMatch] = useState(true);
  const [busy, setBusy] = useState(false);
  const [progress, setProgress] = useState<AIProgress | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [meta, setMeta] = useState<{ engine: string; attempts: number } | null>(null);

  const addExample = () => {
    const t = draft.trim();
    if (!t) return;
    setExamples((cur) => [...cur, { text: t, shouldMatch: draftShouldMatch }]);
    setDraft("");
  };

  const generate = async () => {
    setBusy(true);
    setError(null);
    setMeta(null);
    try {
      const result = await generateRegex(intent.trim(), examples, setProgress);
      onGenerated(result.regex);
      setMeta({ engine: result.engine, attempts: result.attempts });
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
      setProgress(null);
    }
  };

  return (
    <div className="space-y-3">
      <div>
        <label className="text-caption font-bold uppercase text-surface-grey-2">
          Describe the condition in plain English
        </label>
        <textarea
          data-testid="ai-intent"
          rows={2}
          placeholder="e.g. The Fed cuts interest rates by at least 50 basis points"
          value={intent}
          onChange={(e) => setIntent(e.target.value)}
          className="w-full border-2 border-surface-ink bg-paper-0 px-3 py-2 outline-none focus:border-core-orange"
        />
      </div>

      <div>
        <label className="text-caption font-bold uppercase text-surface-grey-2">
          Example headlines (optional — the pattern must agree with these)
        </label>
        <div className="mt-1 flex gap-2">
          <button
            onClick={() => setDraftShouldMatch((v) => !v)}
            data-testid="ai-example-kind"
            className={`border-2 border-surface-ink px-2 text-caption font-bold uppercase ${
              draftShouldMatch ? "bg-system-green/15 text-system-green" : "bg-system-red/10 text-system-red"
            }`}
            title="Toggle whether this example should match"
          >
            {draftShouldMatch ? "matches" : "no match"}
          </button>
          <input
            data-testid="ai-example-input"
            placeholder="Breaking News: Fed slashes rates by 50bps"
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && (e.preventDefault(), addExample())}
            className="min-w-0 flex-1 border-2 border-surface-ink bg-paper-0 px-3 py-2 outline-none focus:border-core-orange"
          />
          <button
            aria-label="Add example"
            onClick={addExample}
            className="border-2 border-surface-ink bg-paper-0 px-3 shadow-[0.125rem_0.125rem_0px_0px_#595959]"
          >
            <Plus size={16} weight="bold" />
          </button>
        </div>
        {examples.length > 0 && (
          <ul className="mt-2 space-y-1" data-testid="ai-example-list">
            {examples.map((ex, i) => (
              <li key={i} className="flex items-center gap-2 border-2 border-surface-ink bg-paper-0 px-2 py-1 text-sm">
                <span
                  className={`text-caption font-bold uppercase ${ex.shouldMatch ? "text-system-green" : "text-system-red"}`}
                >
                  {ex.shouldMatch ? "matches" : "no match"}
                </span>
                <span className="truncate">{ex.text}</span>
                <button
                  aria-label={`Remove example ${ex.text}`}
                  className="ml-auto text-system-red"
                  onClick={() => setExamples((cur) => cur.filter((_, j) => j !== i))}
                >
                  <Trash size={14} />
                </button>
              </li>
            ))}
          </ul>
        )}
      </div>

      <Button
        onClick={generate}
        isLoading={busy}
        disabled={busy || intent.trim().length < 8}
        leftIcon={<Sparkle size={15} weight="fill" />}
        data-testid="ai-generate"
      >
        {currentRegex ? "Regenerate pattern" : "Generate pattern"}
      </Button>

      {busy && progress && (
        <div className="border-2 border-surface-ink bg-paper-main p-2 text-caption" data-testid="ai-progress">
          <div className="font-bold uppercase">{progress.stage}</div>
          {progress.pct !== undefined && (
            <div className="mt-1 h-2 w-full border border-surface-ink bg-paper-0">
              <div className="h-full bg-core-orange" style={{ width: `${progress.pct}%` }} />
            </div>
          )}
          {progress.note && <div className="mt-1 truncate text-surface-grey-2">{progress.note}</div>}
          <div className="mt-1 text-surface-grey-2">
            Runs fully in your browser — the first use downloads the model once (~1 GB, cached after).
          </div>
        </div>
      )}

      {error && (
        <div className="flex items-start gap-1.5 border-2 border-system-red bg-system-red/5 p-2 text-sm text-system-red" data-testid="ai-error">
          <WarningCircle size={16} className="mt-0.5 flex-none" /> {error}
        </div>
      )}

      {currentRegex && !busy && (
        <div data-testid="ai-result">
          <div className="flex items-center gap-1.5 text-caption font-bold uppercase text-surface-grey-2">
            Generated pattern
            {meta && (
              <span className="flex items-center gap-1 font-medium normal-case text-system-green">
                <CheckCircle size={13} weight="fill" /> validated · {meta.engine} · attempt {meta.attempts}
              </span>
            )}
          </div>
          <code className="mt-1 block break-all border-2 border-surface-ink bg-paper-1 px-2 py-1.5 font-mono text-sm">
            {currentRegex}
          </code>
          <p className="mt-1 text-caption text-surface-grey-2">
            Test it against sample headlines below; switch to Advanced to hand-tune.
          </p>
        </div>
      )}
    </div>
  );
}
